gitpod-io/workspace-images

full/Dockerfile

libcurl3 appears to be linked against in case of dugite's git.

add libcurl3

---

full/Dockerfile

This reverts commit cbfc35689168bdc5d7f991ef4604ad663572dde8.
There is a conflict of libcurl3 and libcurl4.

Revert "add libcurl3"

---

full-vnc/Dockerfile
full/Dockerfile

All should be as it was, with some fixes to duplication, version pinning, etc.
I compared the old and new image regarding the environment, `PATH`, and whether everything in the `gitpod` user directory is owned by `gitpod:gitpod`. It seemed fine. (There were a few changes, but those were deliberate, hopefully not breaking anything. See below)
PR #33 has been incorporated in this one.
Potential issues remaining:
* **(important)** the environment & `PATH` differs more or less in all the potential scenarios of the image start (`bash`/`sh`, background/interactive/login/interactive+login, `gitpod`/`root` user). I had issues with this, fixed what needed, but I still want to check a few things based on how we start the image internally in Gitpod
* CLang is rather outdated (there's version 7 …

Streamline & fix to align with Gitpod internals

---

full/Dockerfile

I much prefer it over `top`, and it has an installed size of "only" [225.0 kB](https://packages.debian.org/sid/htop).

Install htop

---

full/Dockerfile

Replace fix keys for rvm.io with dynamically fetched ones following https://rvm.io/rvm/security#alternatives.

Dynamically fetch rvm.io GPG keys

---

.circleci/build_image.sh
.circleci/config.yml

This is based on the configuration we use to build and publish images in https://github.com/JanitorTechnology/dockerfiles.
It builds quite fast, and organizes builds into nice dependency trees:
Many thanks for writing that build script @ishitatsuyuki! 💯

Build and deploy images using CircleCI

---

.circleci/build_image.sh
.circleci/config.yml

It commonly happens that branches in this repository include `/` characters:
- https://github.com/gitpod-io/workspace-images/pull/59#issuecomment-466996060
- https://github.com/gitpod-io/workspace-images/pull/62#issuecomment-469235762
This currently breaks CircleCI builds, because branch names are used in Docker tags, where `/` has a special meaning. To address this, we replace any `/` in branch names with `-` in Docker tags.
Note that this creates a potential tag collision between branches called e.g. `br/anch` and `br-anch`, but I don't consider this a big problem because non-`master` branches are just there for tests.

[circleci] Support building branch names with '/'

---

full/Dockerfile

- installs `musl*` packages to allow to build static binaries with Rust in Gitpod out of the box
- installs `cargo-watch` to enable watch-functionality, e.g.: `cargo watch -x check`

Rust: Enable building of static binaries, install cargo-watch

---

full/Dockerfile

This puts the default installation directory of Ruby gems inside the `/workspace` volume, thus persisting the result of `gem install <gem>` and `bundle install` over workspace restarts.
As suggested in https://github.com/gitpod-io/gitpod/issues/353#issuecomment-470865743.
Fixes https://spectrum.chat/gitpod/general/snapshots-save-the-state-of-the-workspace-what-does-that-include~2edb3776-dfd4-4224-8322-2b1545f35414.

Install Ruby gems in /workspace/.rvm for persistence

---

full/Dockerfile

Should address https://github.com/gitpod-io/gitpod/issues/353 somewhat.
This will not make `rvm install 2.X` persistent, however since `2.4`, `2.5`, and `2.6` will already be pre-installed, you can simply specify this in your `.gitpod.yml`:
```yaml
tasks:
- before: rvm use 2.4
```
This will make sure that your terminals always use Ruby 2.4, even after you restart your workspace.

Pre-install Ruby 2.6, 2.5, 2.4

---

full/Dockerfile

* `python` is `python2`
* all packages to be installed under `/workspace`
⚠️ this introduces a bypass for virtual environments, as those global packages will always be visible.
Closes https://github.com/gitpod-io/workspace-images/issues/55

[python] Use global pip installation target

---

full/Dockerfile

Move `GOPATH` to `/workspace/go` to enable Go modules using `GO111MODULE=auto` (default until Go 1.13).

Move GOPATH to /workspace/go

---

full/Dockerfile

⚠️  This is a breaking change
Unfortunately, a global target installation directory couldn't be used for all regular purposes:
- to enable scripts I added install options
- install options disabled wheels and broke setuptools, see https://github.com/gitpod-io/gitpod/issues/460
To fix this, I propose to use `PYTHONUSERBASE` instead. This means also, that due to a different directory layout the existing `/workspace/.pip-global` won't we useable and needs to be replaced by `/workspace/.pip-modules`. User will need to reinstall modules after restarting an old workspace.

[python] Use user modules by default

---

.circleci/config.yml
full/Dockerfile
rethinkdb/Dockerfile

Needs to be built from source because RethinkDB doesn't provide packages for recent OSes:
http://download.rethinkdb.com/apt/pool/ (last update was on `17-Jul-2017`)

Add new workspace image for projects using RethinkDB

---

full/Dockerfile

this will be automatically set in the Gitpod layer
also, this shouldn't prevent modules from being installed in custom images based on workspace-full.
Fixes https://github.com/gitpod-io/gitpod/issues/517

[python] remove user site from Dockerfile

---

full/Dockerfile

Adds `gopls` to `workspace-full` in preparation for vscode-go v0.10.1

Updated Go tooling for vscode-go 0.10.1

---

full/Dockerfile
rethinkdb/Dockerfile

- The current latest stable version of Clang & co is ~~7~~ 8
- `lld` is much faster than `ld` at linking
- `gdb` is precious for debugging
- `clang-tidy` is a C++ linter that can catch a vast range of dangerous programming errors

Upgrade to clang-9, install gdb, lld-9, clang-tidy-9

---

full/Dockerfile

the selection game implemented in the ms-python extension is won by the highest version number, so let's bump it to the latest.

[python] bump versions of pyenv installations

---

full/Dockerfile

Because HomeBrew comes with an old `openssl`, which breaks some downstream images.
Before we installed `brew`:
```
$ openssl version
OpenSSL 1.1.1b  26 Feb 2019
```
With `brew` installed (now):
```
$ openssl version
OpenSSL 1.0.2s  28 May 2019
```
Hopefully, making HomeBrew a good citizen (i.e. moving it to the end of the `PATH`, not overshadowing everything else) will fix that.

[full] Change HomeBrew binary priority from highest → lowest

---

full/Dockerfile

run with `dazzle-util test run /var/lib/dazzle/tests/*` inside the image

[selftest] Keep tests and `dazzle-util` to enable image self-testing

---

full/Dockerfile

⚠️ I have not tested this upgrade. It could potentially break Go projects in Gitpod.

[full] Upgrade Go from 1.12 → 1.13

---

dotnet/Dockerfile

.NET 3.0 is the currently recommended version on: https://dotnet.microsoft.com/download
Also, .NET 2.2 is in maintenance mode, and support ends on 2019-12-23: https://dotnet.microsoft.com/download/dotnet-core

[full] Upgrade .NET SDK from 2.2 → 3.1

---

full/Dockerfile

Admittedly this is just to get the SHAs to change so a newer version of gradle can be installed, but it works.

Full: update gradle to 6.0.1

---

full/Dockerfile

This optimizes the Rust installation in several ways:
- uninstalls one (unused) toolchain (saves **~1.7GB**)
- updates the installed toolchain to 1.41.0
- installs additional `cargo` plugins for convenience
Thanks to @coolreader18 for the hint with `rustup toolchain install` and deprecated `rls-preview`.

Rust toolchain: Update to 1.41.0, uninstall stable, more tools

---

full/Dockerfile

Both Bcmath and ctype are required for standard Laravel project.

Add PHP Extension: Bcmath and Ctype

---

full/Dockerfile

This way the users will have the latest version of Git (currently 2.25) instead of the older one provided in the Ubuntu repositories (currently 2.20).

Use latest Git instead of the old one provided by Ubuntu

---

postgres/Dockerfile

There're 2 problems.
1.  $PGDATA is only declared, but not used.
2. User cannot configure $PGDATA (for example, they might want it to be a dir in /workspace, like #171) 
This tries to resolve them. 
Note that this is not tested, so reviewers should do it, if CI is not enough.
P.S. `printf "..."` and `printf '...'` are different. env var would be interpolated with "", but not with ''. For instance, try `printf "$foo"` and `printf '$foo'` in your local machine.

fix(postgres): use $PGDATA

---

full/Dockerfile

[Go 1.14](https://golang.org/doc/go1.14) was released on the 25h Feb.
This PR bumps Go to 1.14.

[go] Bump Go to 1.14

---

.circleci/config.yml
CHANGELOG.md
full/Dockerfile

Updates from 10.19.0 -> 12.16.1

[full] Update node version to LTS

---

full/Dockerfile

It seems we had this configuration line forever, but I'm not sure if it's still useful.
Furthermore, it's now broken, because Ubuntu 20.04 doesn't have a `/usr/bin/python` anymore:
```
gitpod /workspace/spring-petclinic $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.04
Release:        19.04
Codename:       disco
gitpod /workspace/spring-petclinic $ ls -larth /usr/bin/python
lrwxrwxrwx 1 root root 7 Mar  4  2019 /usr/bin/python -> python2
```
vs:
```
gitpod /workspace/workspace-images $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu Focal Fossa (development branch)
Release:        20.04
Codename:       focal
gitpod /workspace/workspace-images $ ls -larth /usr/bin/python
ls: cannot access …
```

[full] Don't configure a specific Python PATH in NPM

---

full/Dockerfile

This adds badly needed autocompletion for the cargo command

[full] add bash auto-complete for cargo

---

full-vnc/Dockerfile
gecko/Dockerfile

`gitpod/workspace-full-vnc` should be consistent with `gitpod/workspace-full` in that regard.

[full-vnc] Best practice: Don't stay as "USER root"

---

gecko/Dockerfile

Attempting to fix:
```
[...]
Your version of Mercurial (5.3.1) is sufficiently modern.
Your version of Python (2.7.17) is new enough.
Your version of Rust (1.42.0) is new enough.
Rust supports x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl targets.
Creating global state directory: /home/gitpod/.mozbuild
Traceback (most recent call last):
File "python/mozboot/bin/bootstrap.py", line 202, in <module>
sys.exit(main(sys.argv))
File "python/mozboot/bin/bootstrap.py", line 193, in main
dasboot.bootstrap()
File "python/mozboot/mozboot/bootstrap.py", line 469, in bootstrap
hg=self.instance.which('hg'))
File "python/mozboot/mozboot/bootstrap.py", line 704, in current_firefox_checkout
_warn_if_risky_revision(path)
File "python/mozboot/mozboot/bootstrap.py", line 821, in _warn_if_risky_revision …
```

[gecko] Fix image build

---

dotnet-vnc/Dockerfile
dotnet/Dockerfile

As suggested in https://webcache.googleusercontent.com/search?q=cache:CfIV54IT1KAJ:https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-2004+&cd=1&hl=en&ct=clnk&gl=fr&client=firefox-b-d

[dotnet][dotnet-vnc] Fix image builds

---

CHANGELOG.md
full/Dockerfile

But keep Ruby 2.5, that way we stay with the latest stable Ruby + the most popular Ruby version ([in 2019, according to JetBrains](https://www.jetbrains.com/lp/devecosystem-2019/ruby/)). Also, I'm looking forward to more recent data for 2020.

[full] Upgrade Ruby 2.5 → 2.5.8 and 2.6 → 2.7.1

---

full/Dockerfile

Instead of changing GEM_HOME env var (which gets mutated by rvm), we use custom rvm user config.

Fix ruby rvm paths

---

CHANGELOG.md
full/Dockerfile
full/tests/lang-python.yaml
gecko/Dockerfile

Fixes https://github.com/gitpod-io/gitpod/issues/1540

[full] Make `python` be Python 3 by default (use `pyenv local 2.7.17` to go back to Python 2)

---

gecko/Dockerfile

The base image `gitpod/workspace-full` already comes with Node.js 12.
However, `./mach bootstrap` seems to `apt-get install nodejs nodejs-doc`, which installs a deprecated Node.js version:
```
$ apt search nodejs
Sorting... Done
Full Text Search... Done
nodejs/now 10.19.0~dfsg-3ubuntu1 amd64 [installed,local]
evented I/O for V8 javascript - runtime executable
nodejs-doc/now 10.19.0~dfsg-3ubuntu1 all [installed,local]
API documentation for Node.js, the javascript platform
$ /usr/bin/nodejs --version
v10.19.0
```
This breaks `./mach build`, because it disregards what's in the `PATH` and goes straight to `/usr/bin/nodejs`, and then fails because it wants `> v10.21`.
Removing the deprecated extra Node.js should fix that.

[gecko] Uninstall deprecated Apt version of Node.js

---

full/Dockerfile

As discussed with @AlexTugarev: Installing `pip` also for the system version of Python 3 (i.e. not only in Pyenv's Python 3, which is expected to be the default version) makes it easier to use the system version in Gitpod without too many strange errors / warnings / alerts in the IDE.

[full] Also install 'pip' for system Python 3

---

full/Dockerfile

Should hopefully fix https://github.com/gitpod-io/workspace-images/issues/258 as a side-effect.
See also https://community.gitpod.io/t/scala-gitpod-example-doesnt-work-invalid-formula-error/1572

[full] Update HomeBrew installation steps

---

full/Dockerfile

Otherwise, you get `clang-11` in the PATH, but not the convenient `clang` alias.

[full] Explicitly install package 'clang' to get the corresponding alias for the suffixed binary (e.g. 'clang-11')

---

full/Dockerfile

I face the java version issue at the time of docker image build so I change the version and it install the latest version i.e. Java 11.0.8.fx-zulu
link: https://cdn.azul.com/zulu/bin/zulu11.41.23-ca-fx-jdk11.0.8-linux_x64.tar.gz

Java 11.0.6.fx-zulu is not available

---

full/Dockerfile
full/tests/tool-docker.yaml

This PR adds `dockerd`, `docker` client, `containerd` and [`dive`](https://github.com/wagoodman/dive) to workspace-full.
This is in preparation for fixing https://github.com/gitpod-io/gitpod/issues/52.

add docker to workspace-full

---

full-vnc/Dockerfile

Otherwise, when you scroll on a desktop, it constantly cycles between desktops.
That's super confusing and annoying.

[full-vnc] Change the default number of Openbox virtual desktops from 4 to 1 (footgun)

---

dotnet-vnc/Dockerfile
dotnet/Dockerfile

This upgrades the .NET stacks to .NET 5.0. This also gets rid of the awful  F# Mono installation we used to do as F# is now part of the .NET 5.0 stack.

Upgrade dotnet stacks to .NET 5.0

---

full/Dockerfile
full/tests/lang-rust.yaml

Fixes https://github.com/gitpod-io/workspace-images/issues/124
This PR currently reduces `gitpod/workspace-full` from `7.33 GB` to `6.46 GB`.

Make gitpod/workspace-full image lighter by removing unnecessary/duplicate stuff

---

full/Dockerfile

Fixes errors like:
```
$ brew install hub
...
Error: No similarly named formulae found.
Error: No available formula with the name "wayland" (dependency of hub).
It was migrated from linuxbrew/xorg to homebrew/core.
```

[full] Update Homebrew + CMake dazzle layer

---

full/Dockerfile

14 is the new LTS version.
You can see https://github.com/nodejs/Release.

[full] bump Node.js to 14

---

full/Dockerfile

fix is here: https://github.com/gitpod-io/gitpod/pull/2379

Remove Workaround for `runc` path bug

---

full/Dockerfile
gecko/Dockerfile

using "--no-cache-dir" flag in pip install ,make sure downloaded packages
by pip don't cached on system . This is a best practice which make sure
to fetch from repo instead of using local cached one . Further , in case
of Docker Containers , by restricting caching , we can reduce image size.
In term of stats , it depends upon the number of python packages
multiplied by their respective size . e.g for heavy packages with a lot
of dependencies it reduce a lot by don't caching pip packages.
Further , more detail information can be found at
https://medium.com/sciforce/strategies-of-docker-images-optimization-2ca9cc5719b6
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>

chore : use `--no-cache-dir` flag to `pip`

---

.github/ISSUE_TEMPLATE/config.yml
SECURITY.md

To avoid people ~~like me~~ being an idiots who make an issues about things they didn't know were serious >.<
This configures the issue UI to point the end-users to proper channel alike IRC and Discord on this example:
Signed-off-by: Jacob Hrbek <kreyren@rixotstudio.cz>

templates: Add security notice

---

full/Dockerfile

Side-effect: nukes Node.js Dazzle layer cache to fix https://github.com/gitpod-io/workspace-images/issues/368

[full] Upgrade NVM to v0.37.2

---

base/Dockerfile
base/install-packages
full/Dockerfile
gecko/Dockerfile

fixes https://github.com/apolopena/gitpod-laravel8-starter/issues/46
fixes https://github.com/gitpod-io/gitpod/issues/3352
fixes #339
Update docker compose to latest stable version. Current version [1.25.0](https://github.com/docker/compose/releases/tag/1.25.0) was released in Nov 2019.

Fix issues with apache2 and update docker-compose

---

full/Dockerfile

node-gyp is a core part for Node.js call c/cpp modules. https://www.npmjs.com/package/node-gyp (Weekly download with 9 million ATM)

[full]: add node-gyp as core deps for Node.js

---

dotnet-lts-vnc/Dockerfile
dotnet-lts/Dockerfile
dotnet-vnc/Dockerfile
dotnet/Dockerfile

Changes manual download/unpacking to an install script:
* dotnet-install.sh will keep SDK versions current over time since it installs from a feed
* This defaults to the Current channel (which was already in use) rather than the LTS channel
* Having a separate LTS SDK acquisition will likely require a different workspace (`gitpod/workspace-dotnet-lts` ?)
This was tested here: https://github.com/fslaborg/XPlot/pull/161

Use dotnet-install.sh to acquire .NET SDK

---

full/Dockerfile

Release notes: https://github.com/wagoodman/dive/releases/tag/v0.10.0
Full diff: https://github.com/wagoodman/dive/compare/v0.9.2...v0.10.0

Update dive from 0.9.2 to 0.10.0

---

full/Dockerfile

While working with rust over Gitpod you would always notice that the formatter is missing for `.rs` files(aka Rust project files) and you have to manually install it every-time. Although if I'm not wrong then Gitpod is meant to be bare-bones when it comes to ready to use workspaces ;) And since the additional formatter is being installed for [clang](https://github.com/gitpod-io/workspace-images/blob/409e1707b3cbe6752a894893cd6354fc13d7b8f5/full/Dockerfile#L18) and [golang](https://github.com/gitpod-io/workspace-images/blob/409e1707b3cbe6752a894893cd6354fc13d7b8f5/full/Dockerfile#L100) as well, why not for rustlang :smile: ?
Anyway, `rustfmt` comes by default unless you specify [minimal](https://github.com/gitpod-io/workspace-images/blob/409e1707b3cbe6752a894893cd6354fc13d7b8f5/full/Dockerf …

[full] feat: Add rustfmt component for Rust setup

---

full/Dockerfile

While #213 upgraded Ruby to 2.7 once, but reverted it in e9281a207c4c6b4c7df2e91e9ec81f36ed0652ae, Ruby 2.6.6 has some security vulnerabilities described in https://www.ruby-lang.org/en/news/2021/04/05/ruby-2-6-7-released/.
As Ruby 3.0.1 is also available, we can add it into the full image.

Update Ruby to 2.7.3 in full image

---

full/Dockerfile

Fixes https://github.com/gitpod-io/gitpod/issues/4445
**Explanation**: It looks like a bad version of `~/.nvm/nvm-lazy.sh` got stuck in a Dazzle cache during the development of https://github.com/gitpod-io/workspace-images/pull/411, and then was never updated with the fixes because the Node.js Dazzle layer wasn't modified again in subsequent commits.
It seems a bit wild to me that Dazzle re-uses WIP caches from Pull Requests when deploying to production.

[full] Force Dazzle rebuild of Node.js layer to include newest nvm-lazy.sh

---

postgres/Dockerfile

It does not seem that https://github.com/gitpod-io/workspace-images/pull/417 changes are picked up.

force rebuild of postgres

---

base/Dockerfile

Fixes https://github.com/gitpod-io/gitpod/issues/3284

Display current git branch in the terminal prompt (PS1)

---

base/Dockerfile

Adds `git-lfs` and installs the shell hooks at the system level (which can be overridden by configuring at the user scope).
Related to https://github.com/gitpod-io/gitpod/issues/4852
Tested with
```cd base; docker build -f Dockerfile .```

feat(base): add git-lfs

---

base/Dockerfile

Ripgrep is a handy tool for devs to perform search operations at blazingly fast speeds and pretty less memory consumption.

base/dockerfile: Install ripgrep

---

full/Dockerfile
full/tests/lang-go.yaml

golangci-lint is the defacto go linter. Installing it in full will make it available for everyone to use. 
Worth noting that VSCode will fail silently if your config specifies golangci and it isn't present :-(

[full] Add golangci-lint

---

full/Dockerfile

fixes https://github.com/gitpod-io/gitpod/issues/4886

[python] Set PIP_USER=no

---

.github/ISSUE_TEMPLATE/.config.yml
.github/ISSUE_TEMPLATE/config.yml
full/Dockerfile

An attempt to work around https://github.com/gitpod-io/gitpod/issues/5280
Update HomeBrew by invalidating the Dazzle layer cache with a simple change.
Fixes https://github.com/gitpod-io/gitpod/issues/5280
1. Use the Docker image of this PR in your repository: `gitpod/workspace-full:branch-jx-update-brew-1`
2. Confirm that commands like `brew update` and `brew install stripe/stripe-cli/stripe` work as expected
```release-note
Update HomeBrew in gitpod/workspace-full
```

[full] Force Homebrew layer rebuild

---

full/Dockerfile
full/tests/tool-nix.yaml

Adds the nix package manager to the workspace-full image for the people, like myself, who prefer nix over homebrew.
Fixes https://github.com/gitpod-io/workspace-images/pull/482
Fixes https://github.com/gitpod-io/workspace-images/issues/477
```release-note
- The nix package manger is now available in workspace-full.
```

feat(workspace-full): nix package manager

---

full/Dockerfile
full/tests/lang-clojure.yaml

The build on `master` is currenty broken and this pull request resolves the test that is not passing.
```release-note
NONE
```

fix: resolve broken build

---

full/Dockerfile

Rust 1.58.0 introduces some cool stuff like format strings that I’d like to take advantage of.

Update Rust to 1.58.0

---

.gitpod.Dockerfile

Add an ENV to the .gitpod.Dockerfile in order to trigger creation of a new docker image.
We recently published a new workspace-full image which was created dazzle rewrite.
This will enable us to dogfood.
Fixes # NA
Open this PR in a workspace.
Run `./dazzle-up.sh`. If the build starts then success.
```release-note
None
```

Add ENV to retrigger repo's image build to use latest image

---

dazzle.yaml

Change the base images to workspace-full for the images that had full in the legacy image.
Fixes https://github.com/gitpod-io/workspace-images/issues/675
NA
```release-note
Use full image as base for dotnet-vnc, mysql, postgreql and mongodb
```

Use full image for combinations derived from legacy images

---

.github/CODEOWNERS
.github/workflows/triage.yml

Use GH graphql api to manage triage workflow. Since we are using Projects (Beta), existing actions are not good enough to handle project updates. I tried `srggrs/assign-one-project-github-action@1.2.1` and `https://github.com/alex-page/github-project-automation-plus` but both of them had some form of issues while interacting with beta apis. Since Github Graphql apis are GA and also given as example in the [official docs](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/automating-projects#example-workflow-authenticating-with-a-personal-access-token) it makes sense to use it.
Also Add CODEOWNERS file for auto code reviewer assignment
Fixes https://github.com/gitpod-io/workspace-images/issues/666
The issue label and project assignment can be only tested when this PR …

Use GH graphql api to manage triage workflow

---

chunks/tool-nix/Dockerfile
chunks/tool-nix/chunk.yaml
dazzle.yaml
tests/tool-nix.yaml

Upgrades the version of nix to the latest release (2.6.0). This includes the major 2.4 update, which introduced support for features such as flakes.
N/A
Open a workspace with this image
```shell
gitpod ~ $ nix --version
nix (Nix) 2.6.0
gitpod ~ $ nix run "nixpkgs#hello"
Hello, world!
gitpod ~ $ 
```
```release-note
- Bump nix to 2.6.0
```

feat(nix): bump version to 2.6.0

---

.github/sync-containers.yml
.github/workflows/push-main.yml

Use GAR to build images instead of local registry. This would enable faster builds as GAR would house the previously built chunks.
Fixes partially https://github.com/gitpod-io/workspace-images/issues/713
Can be only tested after merge.
```release-note
None
```

Use GAR for image building and cache for push-main.yml workflow

---

.github/registries.conf
.github/workflows/dockerhub-release.yml
.github/workflows/push-main.yml

The `push-main.yml` workflow would build new images whenver there is a merge to the master branch.
It will rename and copy the images along with datetimestamp to GAR.
It will also retag the new image tag with `latest` tag.
It will push all the tags of images in GAR to Dockerhub via skopeo sync.
Do not push new image tags from GAR to Docker hub when there are merges to master.
Create a new workflow `dockerhub-release.yml` which can be only triggered manually.
This workflow will copy all the tags including the `latest` tag of workspace images to Docker Hub from GAR.
Additionally -  I removed the `registries.conf` file which is no more applicable as we switched to GAR.
Fix https://github.com/gitpod-io/workspace-images/issues/728
NA. Can be only tested after merge.
```release-note
None
```

Sync images tags to Dockerhub using manual Action

---

.github/update-dazzle-for-pr.py
.github/workflows/pull-request.yml

Use GAR to build images instead of local registry.
This would enable faster builds as GAR would house the previously built chunks.
Modify dazzle.yaml file to rename the combination so that two PRs do not race to write to the same tag.
Use PR number suffix to distinguish builds.
Fixes partially https://github.com/gitpod-io/workspace-images/issues/713
See the pull-request.yml action for this PR. It is already using GAR.
```release-note
None
```

Use GAR to build images for pull-request.yml workflow

---

.github/gargc.sh
.github/workflows/pr-registry-cleanup.yml

Every PR results in creation of images and layers. These are stored in the GAR. We don't need layers created from old PRs which are merged. Since there is no way to identify the sha of a layer based on the PR, we delete all the layers and tags in the GAR which are older than 4 days. In some cases when a PR is open longer than 4 days a manual retrigger of build or a new push to the PR will result in rebuilding of layers. This is not so bad considering the amount of storage the stale layers will consume.
Partially Fixes https://github.com/gitpod-io/workspace-images/issues/713
I tested the changes by [triggering them on a pull_request](https://github.com/gitpod-io/workspace-images/runs/5350633387?check_suite_focus=true) event and it succeeded.
```release-note
None
```

Delete older image tags and layers for docker-dev-pr/workspace-base-images-pr image

---

.github/workflows/triage.yml

Fix incorrect ISSUE_ID for triage workflow
Fixes failing triage workflow for issues e.g. [[1](https://github.com/gitpod-io/workspace-images/actions/runs/1906402367)]
Can be tested only post merge.
```release-note
None
```

Fix incorrect ISSUE_ID for triage workflow

---

chunks/tool-docker/Dockerfile
tests/tool-docker.yaml

The docker compose command (_not_ docker-compose) is not available. We already download the binary but it is not in the location that docker expects. See [installation instructions.](https://docs.docker.com/compose/cli-command/#install-on-linux).
Fixes #577
- Run workspace image with docker tools installed
- Call docker compose -> The command should be available
```release-note
Make docker compose subcommand available
```

Ensure docker compose subcommand is available

---

.github/workflows/triage.yml

To have a single source of truth, all PRs should be continued to be
listed using the team label instead of adding it to team project board.
NA
This can be only tested post merge.
The issue triage should continue to work and PRs should not get auto assigned to project after this is merged.
```release-note
None
```

Get rid of PR assignment to Project

---

.github/promote-images.yml
.github/workflows/dockerhub-release.yml
.github/workflows/push-main.yml

The `push-main.yml` workflow would build new images whenever there is a merge to the master branch.
It will rename and copy the images along with datetimestamp to GAR.
It will also retag the new image tag with `latest` tag.
The `dockerhub-release.yml` workflow syncs all tags of images from GAR to Docker Hub.
The `push-main.yml` workflow will sync only date time stamp tagged images from GAR to dockerhub using skopeo.
The `dockerhub-release.yml` will copy only the `latest` tag of workspace images to Docker Hub from GAR.
So, everytime there is a merge to the master branch new set of images will be release to public on Docker Hub, however, it will not update the latest tag.
You can see [skopeo doc](https://github.com/containers/skopeo/blob/main/docs/skopeo-sync.1.md) to learn more on the yaml …

Promote date time stamped tags to Dockerhub

---

.github/promote-images.yml

`dotnet-vnc` was reintroduced due to [bad copy-paste](https://github.com/gitpod-io/workspace-images/pull/753/files#diff-f3ecae09629802a1f735c45473eb2fb4389dfcc37fbea02d54bbfbf3c6901e26R19). Replace it with `dotnet`
Fixes NA
NA
```release-note
None
```

Fix release image regression for dotnet

---

chunks/lang-rust/Dockerfile

Adds clippy to rust chunk
Fixes ##755
- Open workspace
- Call cargo clippy
```release-note
Add clippy to the rust installation
```

Add clippy to rust chunk

---

.github/workflows/lint.yml
.github/workflows/push-main.yml
CONTRIBUTING.md

Update default branch name to `main`. Actual branch name has already been renamed.
Fixes https://github.com/gitpod-io/workspace-images/issues/643
Workflow changes can only be tested post merge to the main branch
```release-note
None
```

Update default branch name to `main`

---

chunks/lang-rust/Dockerfile

CARGO specific env var modifications are now done inside workspace-session but not for docker env.
Fixes [this on discord](https://canary.discord.com/channels/816244985187008514/946731644465852466/946805048116121640)
```release-note
```

fix(lang-rust): Custom dockerfile issue for cargo-install to non-existent /workspace dir

---

.gitignore
.gitpod.Dockerfile
.gitpod.yml
CONTRIBUTING.md
dazzle-up.sh

Update `dazzle.yaml` to take inputs from user to build chunks and create a combination.
Fixes https://github.com/gitpod-io/workspace-images/issues/763
Run `.dazzle-up.sh`, you should see that all the chunks are built and all the combinations as specified in `dazzle.yaml` are built.
To build specific chunks and combine those chunks use something like this:
```console
./dazzle-up.sh  -c chunk1 -c chunk2 -n combo
``` 
a working example:
```console
./dazzle-up.sh  -c lang-c -c dep-cacert-update -n mychangecombo
```
```release-note
None
```

Allow building specific chunks locally

---

chunks/lang-java/Dockerfile

Fix test that gets stuck during build.
The `lang-java.yaml` test :
```yaml
- desc: it should run sdk
command: [sdk v]
entrypoint: [bash, -i, -c]
assert:
- status == 0
- stdout.indexOf("SDKMAN") != -1
```
gets stuck because the `sdk v` produces an interactive shell asking user to upgrade the sdkman version. 
```console
gitpod ~ $ sdk v
==== BROADCAST =================================================================
* 2022-03-10: grails 5.1.3 available on SDKMAN!
* 2022-03-10: doctoolchain 2.0.5 available on SDKMAN! https://doctoolchain.github.io/docToolchain/v2.0.x/030_news/2022/2.0.5-release.html
* 2022-03-10: jbang 0.91.0 available on SDKMAN! https://github.com/jbangdev/jbang/releases/tag/v0.91.0
================================================================================
SDKMAN …
```

Fix test that gets stuck

---

.github/workflows/push-main.yml

No
This will push timestamped images to Docker Hub sooner for users.
Continue waiting for approval from the workspace team, which incurs a delay.
None. We'll continue requiring approval to tag images as latest on Docker Hub (we want to time that with building of our packer image so we can cache images).

Run push-main w/o env approval

---

.github/workflows/dockerhub-release.yml
.github/workflows/push-main.yml

1. Revert previous commit which removed env from push-main.yml
2. Update dockerhub-release.yml workflow env
The env `production-restricted` is newly created and hosts the same credentials of Dockerhub.
It always require manual approval.
The existing env `production` is updated to remove manual approval.
Fixes NA
Merging this PR should auto run build from main without approval/
```release-note
None
```

Use dedicated environment for dockerhub-release.yml workflow

---

.gitpod.Dockerfile
.gitpod.yml

`shellcheck` binary is missing but the extension is added on `.gitpod.yml`
Also, I think it's faster if we install dazzle from dockerfile like it's done for buildkit too 😄 
Update: I had a lot of trouble with `pre-commit` on the CI side but thankfully @princerachit was able to help out, so it's better to use `pre-commit` beforehand to reduce hassle.
Fixes #
```release-note
```

refactor: Gitpod config files

---

chunks/tool-postgresql/Dockerfile
tests/tool-postgresql.yaml

`/workspace` dir is non-existent and will get overlapped by gitpod bind mounts on `/workspace` during workspace start.
Fixes #705 
https://gitpod.io/#https://github.com/axonasif/test/tree/postgresql-test
```release-note
```

fix(tool-postgresql): Non-existent /workspace dir

---

.github/workflows/pull-request.yml
.github/workflows/push-main.yml
.gitpod.Dockerfile

Update to support latest dazzle, includes:
https://github.com/gitpod-io/dazzle/releases/tag/v0.1.9
https://github.com/gitpod-io/dazzle/releases/tag/v0.1.10
1. The PR actions must pass (which builds, pushes, and pulls image from an in-memory registry)
2. After a merge to main, we must be able to use the timestamped images with Gitpod

Upgrade to dazzle 0.1.10

---

base/Dockerfile

Packages like [`cowsay`](https://packages.ubuntu.com/bionic/all/cowsay/filelist) get installed at `/usr/games` but it's not on PATH. Although I'm not sure if what I did on this PR is the recommended approach, please suggest.
Fixes https://app.frontapp.com/open/cnv_ix5jz62
```release-note
/usr/games is now added on PATH for packages like cowsay
```

fix: /usr/games missing PATH entry

---

.github/workflows/push-main.yml

Will fix the token timeout on skopeo sync at the end of our push-main flow.
Ref: https://github.com/gitpod-io/workspace-images/runs/5756757882?check_suite_focus=true

Log in again to extend GAR access_token

---

.github/workflows/push-main.yml

The previous PR had a linter error. I've given the authN again step a unique ID, and leveraged it accordingly in the following step to log into GAR with skopeo.

Use a unique ID to authenticate with Google again

---

.github/promote-images.yml
.github/sync-containers.yml
chunks/lang-elixir/Dockerfile
dazzle.yaml
tests/lang-elixir.yaml

Create new `workspace-elixir` image for elixir based gitpod projects. This is to add a new chunk, and make a standalone `workspace-elixir` image based off `workspace-base`. There is no intent to add this to `workspace-full`
Implements #775 
Tests included in tests/lang-elixir.yaml (version output testing, latest elixir from https://www.erlang-solutions.com/downloads/)
```
add workspace-elixir image
```
This adds a standard elixir and erlang toolchain workspace to the available gitpod workspace images for quicker bootstrapping of existing projects.

[feat] add lang-elixir workspace chunk and image

---

.autofix/fixers/update-lang-node.js
.autofix/fixers/update-lang-python.js
chunks/lang-node/chunk.yaml
dazzle.yaml
tests/lang-node.yaml

Adds a fixer that updates node versions
Partially fixes #661
- Open workspace
- Clone autofix from https://github.com/autofix-dev/autofix into e.g /workspace/autofix & npm install
- Change node versions in chunk.yaml to older versions
- Start autofix with npx autofix
- -> Node versions should have been updated
```release-note
None
```

Add node fixer

---

chunks/tool-yugabytedb/Dockerfile

Signed-off-by: Srinivasa Vasu <srinivasan.surprise@gmail.com>
An optional `.nopreload` file as part of the repo restricts the workspace from installation & config of the DB. By default, when the workspace launches, DB will be initialized and running. This optional file gives the flexibility to control the initialization behavior. With the `.nopreload` file, users can control the DB via the .gitpod.yml file.

An optional preload flag to control the YugabyteDB initialization

---

.github/promote-images.yml
.github/sync-containers.yml
dazzle.yaml

Adds a minimal image variant with only the nix tool. This is useful for projects that leverage nix entirely for dependency management.
n/a
```release-note
Add new nix image
```
n/a

Add nix image

---

chunks/lang-java/Dockerfile

sdkman uses a new flag to control self update. This PR updates that flag to the sdkman config in order to avoid asking user if they want to update the sdkman version. This as a result also fixes failing main branch builds.
NA
NA
```release-note
None
```

Disable sdkman self update feature using new flag

---

chunks/tool-docker/Dockerfile
tests/tool-docker.yaml

docker compose v2.2.3 has several bugs that have been fixed in newer versions. The latest version at the moment is 2.4.1.
Related to https://github.com/gitpod-io/workspace-images/issues/577
Run a workspace and check `docker compose version` to see that it's v2.4.1.
```release-note
NONE
```

update version of docker compose

---

chunks/lang-rust/Dockerfile
chunks/lang-rust/rustup
tests/lang-rust.yaml

`rustup toolchain install <toolchain>` command was conflicting with the wrapper script of it.
Also, some tiny optimizations was done. Now this image consumes `214MB` less space as we get rid of the unnecessary `$HOME/.cargo/registry` 🥳
Fixes #[this-on-discord](https://discord.com/channels/816244985187008514/966633482619084800/966633485156626442), reported by @jcornaz
- Run a docker container of the `lang-rust`(workspace-rust) chunk.
- Run `rustup toolchain install stable nightly`
- Run `cargo new /tmp/foo` to check cargo is properly functioning.
```release-note
```

refactor(lang-rust): Optimize the image and fix `rustup toolchain install` issue

---

chunks/tool-tailscale/Dockerfile
tests/lang-rust.yaml

Adding PGP keys to apt does not work with dazzle.
This change removes the the source list to avoid this problem in subsequent `apt-get` operations.

[tailscale] Fix tailscale chunk

---

chunks/lang-node/chunk.yaml
dazzle.yaml
tests/lang-node.yaml

Updates (non-LTS) Node.js from 17 to 18 in `gitpod/workspace-node` image.
https://github.com/nodejs/node/blob/3a6b9759810922130c1389bf67d89d50fc8dd26a/doc/changelogs/CHANGELOG_V18.md#18.0.0
> 2022-04-19, Version 18.0.0 (Current), @BethGriggs
Fixes #811
TBD
```release-note
Bump node.js to v18.0.0 in gitpod/workspace-node image.
```
* No
* Are you sure? If so, nothing to do here.

Update non-LTS node from 17 to 18

---

chunks/tool-vnc/.Xresources
chunks/tool-vnc/.xinitrc
chunks/tool-vnc/Dockerfile
chunks/tool-vnc/gp-vncsession

Now `xfdesktop` starts in less than a second, resulting in a faster vncserver startup.
Basically I had no intentions of optimizing, it's just I was working on https://github.com/gitpod-io/template-flutter/pull/9 and Xfce was showing an error that `xrdb` command is missing, so I installed `x11-xserver-utils` and apparently Xfce starts faster now.
Also, I learned that a few unnecessary things can be removed.
Fixes #
```release-note
```

refactor(vnc): Install `x11-xserver-utils` and some optimizations

---

chunks/lang-ruby/chunk.yaml
tests/lang-ruby.yaml

Update Ruby from 3.1.0 and 2.7.5 to 3.1.2 and 2.7.6.
- ruby 3.1.x
- https://www.ruby-lang.org/en/news/2022/02/18/ruby-3-1-1-released/
- https://www.ruby-lang.org/en/news/2022/04/12/ruby-3-1-2-released/
- ruby 2.7.x
- https://www.ruby-lang.org/en/news/2022/04/12/ruby-2-7-6-released/
Trigger the CI pipeline for this PR.
```release-note
Bump Ruby to 3.1.2
Bump Ruby to 2.7.6
```
* No

Update Ruby to 3.1.2 and 2.7.6

---

.github/workflows/pull-request.yml
.github/workflows/push-main.yml
.gitpod.Dockerfile

```release-note
Update buildkit to v0.10.2 and do not hide install errors
```

Update buildkit to v0.10.2 and do not hide install errors

---

chunks/lang-go/chunk.yaml
dazzle.yaml

Updated go to 1.18.2. The latest stable relase.
[lang-go] Upgraded to 1.18.2

Updated go to 1.18.2

---

base/Dockerfile
chunks/lang-rust/Dockerfile

Rust is installed using rustup which is supposed to install rust only for current user and not other users including root. See this [comment](https://github.com/gitpod-io/workspace-images/issues/608#issuecomment-1125681443) for more explanation. Adding bash completion for rust is meaningless for other users as they don't have rust installed.
The changes in the base image are required as the official bash-completion readme suggests to use the dir `.local/share/bash-completion/completions/rustup`
Also, `rustup completions bash` suggests [the same](https://rust-lang.github.io/rustup/installation/index.html#enable-tab-completion-for-bash-fish-zsh-or-powershell).
Fixes https://github.com/gitpod-io/workspace-images/issues/608
Fastest way to test this is to create the rust combination and test …

Install rust completions for gitpod user only

---

.github/workflows/dockerhub-release.yml

Push images every Tuesday at 10 am UTC. 
Fixes #836 
```release-note
Push latest workspace images to Dockerhub every Tuesday
```

Schedule push of latest images to Dockerhub

---

chunks/tool-brew/Dockerfile

Rebuild the `brew` layer. 
This looks like it was last done in September 2021 (#502) and some packages are now quite out of date, requiring a lengthy `brew update` operation to make the latest versions available.
Fixes #
```release-note
Update `brew` layer to get recent versions of all available homebrew packages
```

Rebuild homebrew layer

---

chunks/tool-nix/Dockerfile

This change adds the installation of `direnv`, an important tool when working with Nix. 
Fixes #847
* The command `direnv` will be available in bash
* Any repo configured to use direnv (and uses the default bashrc) will have direnv activated upon opening a terminal session with bash.
```release-note
Nix image includes direnv
```

chore(chunks/tool-nix): Install direnv

---

.github/promote-images.yml
.github/sync-containers.yml
README.md
dazzle.yaml

Signed-off-by: Takuya Noguchi [takninnovationresearch@gmail.com](https://github.com/sponsors/tnir)
Deprecate [workspace-python-3.6](https://hub.docker.com/r/gitpod/workspace-python-3.6/tags) image as Python 3.6 got EOL in 2021.
- Fixes #857
See if there is no new build for `gitpod/workspace-python-3.6`.
```release-note
Deprecate gitpod/workspace-python-3.6 image. Use gitpod/workspace-python-3.7 or higher.
```
* No

Deprecate workspace-python-3.6 image

---

.github/promote-images.yml
.github/sync-containers.yml
README.md
chunks/lang-ruby/chunk.yaml
dazzle.yaml
tests/lang-ruby.yaml

Signed-off-by: Takuya Noguchi [takninnovationresearch@gmail.com](https://github.com/sponsors/tnir)
Add ruby-3.0 and ruby-3.1 images. ruby-3.1 is required as ruby-3 will be upgraded to 3.2 in 6 months.
Fixes #859
See builds.
```release-note
Add images for Ruby 3.0 and 3.1
```
* No

Add ruby-3.0 and ruby-3.1 images

---

chunks/tool-nix/Dockerfile

This whitelists the `/workspace` directory so that users are not required to run `direnv allow` in a new workspace.
User will not be prompted to run `direnv allow` in a new workspace where a `.envrc` file is present.
```release-note
`direnv allow` is no longer required
```

chore(chunks/tool-nix): Whitelist /workspace in direnv

---

.github/workflows/push-main.yml

Extends the `access_token_lifetime` to 3 hours (10800s) the default value is 1 hour (3600s). 
Reference to
- https://github.com/google-github-actions/auth#generating-oauth-20-access-tokens
- https://cloud.google.com/resource-manager/docs/organization-policy/restricting-service-accounts#extend_oauth_ttl
We added the list constraint `constraints/iam.allowServiceAccountCredentialLifetimeExtension` to the service account `workspace-images-gha-sa@gitpod-artifacts.iam.gserviceaccount.com` already.
Reference to https://console.cloud.google.com/iam-admin/orgpolicies/iam-allowServiceAccountCredentialLifetimeExtension?project=gitpod-artifacts&supportedpurview=project
Fixes https://github.com/gitpod-io/gitpod/issues/11067
```release-note
None
```
N/A

Extends the access token lifetime

---

chunks/tool-vnc/Dockerfile

https://github.com/gitpod-io/workspace-images/issues/872#issuecomment-1179189367
Fixes https://github.com/gitpod-io/workspace-images/issues/872
I pushed the image to my personal docker account and using here for testing, so you could:
- Create a new workspace from here:
- Run `gp preview $(gp url 6080) --external && chromium --start-fullscreen google.com`
- It should not display the welcome screen
- It should not prompt to set itself as the default browser.
```release-note
fix workspace-full-vnc ungoogled_chromium regression
```

fix(tool-vnc): Fallback to google-chrome from ungoogled_chromium

---

dazzle.yaml

Update Ruby from 2.7 to 3.1 in [gitpod/workspace-full](https://hub.docker.com/r/gitpod/workspace-full).
Fixes #886
Check it out: https://github.com/gitpod-io/workspace-images/runs/7464292883?check_suite_focus=true
```release-note
!Upgrade Ruby from 2.7 to 3.1 in workspace-full image
```
* No

Update Ruby from 2.7 to 3.1 in gitpod/workspace-full

---

.gitpod.yml

gp await-port was deprecated in favor of ports await.
cf. https://github.com/gitpod-io/gitpod/pull/10538
Open a Gitpod workspace in review app.
n/a
* No
Signed-off-by: Takuya Noguchi [takninnovationresearch@gmail.com](https://github.com/sponsors/tnir)

Update await-port with ports await in gp-cli

---

chunks/lang-c/Dockerfile

Fix clang issues
```
cannot test chunk lang-c: failed to solve: process "/bin/sh -c curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | sudo gpg --dearmor -o /usr/share/keyrings/llvm-archive-keyring.gpg     && echo \"deb [signed-by=/usr/share/keyrings/llvm-archive-keyring.gpg] http://apt.llvm.org/focal/     llvm-toolchain-focal main\" | sudo tee /etc/apt/sources.list.d/llvm.list > /dev/null     && apt update     && install-packages         clang         clangd         clang-format         clang-tidy         gdb         lld" did not complete successfully: exit code: 100
#6 7.805 The following packages have unmet dependencies:
#6 7.889  clang : Depends: clang-15 (>= 15~) but it is not installable
#6 7.889  clang-format : Depends: clang-format-15 (>= 15~) but it is not installable
#6 …
```

Update clang to v15

---

chunks/lang-python/Dockerfile
chunks/lang-python/pyenv.d/exec/gitpod.bash
chunks/lang-python/pyenv.d/rehash/gitpod.bash
chunks/lang-python/pyenv.d/which/gitpod.bash
chunks/lang-python/python_bash_hook
chunks/lang-python/python_hook.bash
chunks/lang-python/userbase.bash
tests/lang-python.yaml

```
fix: ms-python.python using system python as interpreter by default instead of pyenv and static PYTHONUSERBASE
```
`ms-python.python` defaults to the system(`/usr/bin/python*`) instead of our customized `pyenv` setup under `$HOME/.pyenv`, which causes issues as from the terminal `pyenv` python interpreters are used but not `/usr/bin/python*`. So `ms-python.python` is then not aware of pyenv, causing issues such as:
1. User is confused why their `import` isn't working on VSCode editor
2. User is confused why auto complete/IntelliSense isn't working for python
3. Extensions that depend on [`ms-python.python` API](https://github.com/microsoft/vscode-python/wiki/Proposed-Environment-APIs#environment-apis) fails to locate their python dependencies, for example …

fix(lang-python): VSCode IntelliSense and DBT extension not working

---

chunks/lang-python/Dockerfile

> Poetry 1.2 drops runtime support for Python 2.7, 3.5 and 3.6. Running Poetry on these versions is now untested and unsupported.
https://python-poetry.org/blog/announcing-poetry-1.2.0/#dropping-support-for-python-27-35-and-36-as-runtimes
Building works fine
```release-note
workspace-images: The workspace image of python 3.6 should use old poetry
```

Latest poetry doesn't support python 3.6

---

chunks/tool-nix/chunk.yaml
dazzle.yaml
tests/tool-nix.yaml

Upgraded Nix Version from 2.6 -> 2.11
Latest Release Notes ([read here](https://nixos.org/manual/nix/stable/release-notes/rl-2.11.html))
---
> Signed-off-by: Siddhant Khare <siddhant@gitpod.io>

chore: bump nix version

---

chunks/tool-chrome/Dockerfile
chunks/tool-vnc/Dockerfile
dazzle.yaml

I feel really unconveninent without it in full image. I checked the size, it's only around 130m increase.
It should be in full in the long run.
This will make frontend e2e testing like cypress and Puppeteer more out of the box.
Also benefit for development like qt, jetbrains plugin development, gitbook generating.
context: https://github.com/gitpod-io/workspace-images/pull/471/
Fixes #
```release-note
```

Refactor installation of Chrome on the VNC image

---

chunks/lang-python/python_hook.bash

This time it will handle errors properly and will not log anything on the attached pty but write to `/tmp/.vscode::add_settings.log` file if any error occurs. Will always return true on the parent shell process.
~~Reverts the change that inconsistently causes [this](https://gitpod.slack.com/archives/C01KGM9BH54/p1663747428135699)
It was mainly due to the parent directory not being present before the file creation. But since https://github.com/gitpod-io/gitpod/issues/13029 is being worked out, so we no longer need to fix it here or handle this.~~ In the future we can get rid of this function and use a native built-in gitpod method once we have.
```bash
docker build --build-arg base=gitpod/workspace-base --build-arg PYTHON_VERSION=3.8.13 -t python chunks/lang-python
rm -f …
```

refactor: python_hook.bash

---

dazzle.yaml

Update workspace-full image to use go 1.19.1.
```release-note
```

update go to v1.19.1 in workspace-full

---

chunks/lang-go/Dockerfile

That tool is missing as Go extension wants it always

install missing staticcheck

---

.github/workflows/dockerhub-release.yml
.github/workflows/push-main.yml

Use OCI manifests for the publication of the images instead of docker.
The goal here is to enable the research of lazy snapshotters.
- Use oci-tool to verify the published images use OCI instead docker media types

Copy images using OCI manifests

---

chunks/tool-brew/Dockerfile

To get the latest available versions of packages without users having to run `brew update` first.
```release-note
Update `brew` layer to get recent versions of all available homebrew packages
```

Rebuild `brew` layer

---

chunks/tool-tailscale/Dockerfile

This way users do not have DNS issues "out of the box".
Related to https://github.com/gitpod-io/website/pull/2908
After this is merged to main, we'll be able to create a workspace using timestamped image.
Beforehand, you may run: `./build-chunk.sh -c tool-tailscale`
```release-note
Use tailscale 1.32 or later and avoid DNS issues
```

Fix tailscale ssh

---

.markdownlint.yaml
README.md

This is a part of gitpod-io/website#2341
```release-note
NONE
```

docs: add architecture info & dockerhub url

---

chunks/tool-postgresql/Dockerfile
chunks/tool-postgresql/postgresql-hook.bash
tests/lang-python.yaml
tests/tool-postgresql.yaml

More context [here](https://gitpod.slack.com/archives/C01RC164G48/p1667306470780959) (internal - slack).
Fixes https://github.com/gitpod-io/workspace-images/issues/432
- Parallel starts.
- Autostop server on workspace shutdown.
- Faster shell startup by using subprocess (top: before, down: after)
- Workspace: https://gitpod.io/#imagebuild/https://github.com/axonasif/test/tree/postgresql-test
- To test in existing workspace with race condition simulation:
```bash
docker run -it axonasif/postgresql:latest sh -c 'for _ in 1 2 3 4 5; do bash -lic "true" & done; wait'
```
- Ensure no postgres server related errors are found on the terminal and the server is running:
```bash
docker run -it axonasif/postgresql:latest sh -c 'for _ in 1 2 3 4 5; do bash -lic "true" & done; wait; sleep 3; ps -fax | …
```

fix(tool-postgresql): Race condition

---

tests/lang-rust.yaml

I broke the tests for the rust-lang chunk in #996 . This PR adjusts the failing test, so it passes again.
Previously we tested that `cargo add --help` outputs the string `cargo-add`, but it does not do that anymore with the latest rust version. I adjusted it to test for `cargo add` instead. The test should probably be removed, because if `cargo add --help` exits with code 0 the subcommand exists.

Fix failed test for rust chunk

---

tests/lang-python.yaml

These tests sometimes pass, but often cycle forever, causing builds to take too long or timeout/fail.
Related: https://github.com/gitpod-io/workspace-images/issues/1000

[tests] disable brittle python tests

---

.github/workflows/pull-request.yml
.github/workflows/push-main.yml
.gitpod.Dockerfile

Update buildkit and dazzle
n.a.
- Open PR in Gitpod
```release-note
Update dazzle to 0.1.13 and buildkit to 0.10.6
```

Update buildkit and dazzle

---

.github/promote-images.yml
.github/sync-containers.yml
chunks/lang-python/chunk.yaml
dazzle.yaml

Create image for python 3.11
Fixes https://github.com/gitpod-io/workspace-images/issues/993
- Open workspace
- ./build-combo.sh python-3.11
- docker run --rm -it localhost:5000/dazzle:python-3.11 sh
- python --version
```release-note
Create image for python 3.11
```

Create image for python 3.11 and remove EOL python 3.6

---

.github/promote-images.yml
.github/sync-containers.yml
chunks/lang-ruby/chunk.yaml
dazzle.yaml
tests/lang-ruby.yaml

- Add ruby-3.2 image (expected to be released at `https://hub.docker.com/r/gitpod/workspace-ruby-3.2`)
- Update [ruby-3](https://hub.docker.com/r/gitpod/workspace-ruby-3) from 3.1.2 to 3.2.0
Fixes #1004
n/a
```release-note
add ruby-3.2 image
update ruby-3 image from 3.1.2 to 3.2.0
```
* No
* Are you sure? If so, nothing to do here.
Signed-off-by: Takuya Noguchi [takninnovationresearch@gmail.com](https://github.com/sponsors/tnir)

Add ruby-3.2 image and update ruby-3 from 3.1.2 to 3.2.0

---

chunks/lang-python/chunk.yaml

Python 3.7, 3.8, 3.9, 3.10 using their latest releases:
- `3.7.13` -> `3.7.16`
- `3.8.13` -> `3.8.16`
- `3.9.13` -> `3.9.16`
- `3.10.6` -> `3.10.9`
```release-note
Python 3.7, 3.8, 3.9, 3.10 using their latest releases
```

chore: update python 3 images

---

chunks/lang-python/Dockerfile
chunks/lang-python/python_hook.bash
tests/lang-python.yaml

Our custom `pyenv install` hook wasn't working anymore for this new feature of `pyenv install` command:
- https://github.com/pyenv/pyenv/pull/2568
We can patch our hook later to adapt to this change but an quick and reliable solution is to pin `pyenv` to a specific commit, which is recent enough.
Fixes https://github.com/gitpod-io/workspace-images/issues/1000
```release-note
```

chore: pin pyenv version

---

chunks/lang-go/chunk.yaml
dazzle.yaml

Update Go to versions 1.19.5 and 1.18.10
Fixes #
```release-note
```

update Go to 1.19.5 and 1.18.10

---

.github/promote-images.yml
.github/sync-containers.yml
buildkitd.toml
dazzle.yaml

Do not use workspace-full for gitpod development to reduce the size and avoid 3m pulling images in CI
/hold

Add new gitpod-dev image

---

.github/workflows/dockerhub-release.yml
.github/workflows/push-main.yml

* Run skopeo in a container, to remove the dependency on apt and opensuse.org. This way we can get newer versions of skopeo more quickly.
* Running skopeo in a container is working well in the `dockerhub-release` [action](https://github.com/gitpod-io/workspace-images/actions/runs/5537836253/jobs/10107108142#step:9:345). You'll notice it failed, though. This is because the `push-main` action is silently failing, not uploading the `latest` to GAR, at least for our new `gitpod-dev` image, but perhaps others too.
*  We need to fix `push-main` to fix `dockerhub-release`, hence this PR.
* Improveserror handling when uploading to GAR (we've been silently failing on upload) [ref](https://github.com/gitpod-io/workspace-images/actions/runs/5506807104/jobs/10035963596#step:16:55)
* I …

[.github] refactor push-main.yml action

---

.github/workflows/push-main.yml

The container that we're preparing to run skopeo in [needs](https://github.com/gitpod-io/workspace-images/actions/runs/5543383131/jobs/10119315364#step:18:28) to also include a copy of the promote-images.yml file for `skopeo sync`.

[github] fix push-main.yml and `skopeo sync`

---

.github/workflows/push-main.yml

Oops, the path wasn't absolute in the step, and now that we're using a bind mount, this would help a lot.
Relates to WKS-306

[.github] fix path associated with push-main.yml and `skopeo sync`

---

chunks/tool-brew/Dockerfile

Related to https://github.com/Homebrew/homebrew-bundle/issues/1227, current Homebrew version is outdated and failing with some specific taps.
Upgrading Homebrew to the latest version (`4.0.28`) solves the problem.
https://github.com/Homebrew/homebrew-bundle/issues/1227
1. Create a Brew bundle file with the following content:
```yaml
tap "homebrew/bundle"
tap "homebrew/core"
brew "zplug"
```
2. Run `brew bundle install`
3. Installation should succeed
* No
/hold

Upgrade Homebrew to 4.0.28

---

.github/workflows/push-main.yml
.github/workflows/push-main/upload_image.sh

* push-main.yml: produce a viable command string for each image we'd like to upload
* upload_image.sh: was echoing (oops), instead of actually uploading
This can be tested by executing `./foo.sh` in https://gitpod.io#snapshot/c862c9e3-e210-4498-aa7d-5d798c3cdd5e

[.github] fix push-main.yml and upload to GAR

---

.github/workflows/push-main.yml

In response to the failure from: https://github.com/gitpod-io/workspace-images/actions/runs/5570294337/jobs/10174237617

[.github] better handle trailing newlines when uploading to GAR

---

.github/workflows/push-main.yml

🤦we're using yq 3, not yq 4, this explains why it worked fine in a Gitpod workspace, because I initially used `brew install yq` instead of `sudo pip3 install yq` to install yq.

[.github] rewrite parsing of sync-containers to work with yq 3

---

.github/workflows/dockerhub-release.yml

* limit promote-latest to schedule (which uses main) or workflow_dispatch (but, limit it to main)
* notify in Slack when releases are done
* this avoids the `production-restricted` environment, which required a human to approve the release
Fixes n/a
Run the action manually, it should notify in `#feature-workspace-images` with success or the failure and actual status.
/hold

[.github] automate production release

---

.github/workflows/dockerhub-release.yml

Looks like there's runner trouble, or, a need to upgrade to v4 for actions/checkout.
Ref: https://github.com/actions/checkout/issues/1448
Either way, we should notify when this job is not successful.

[.github] don't skip notify on failure of dependent jobs

---

.github/promote-images.yml
.github/sync-containers.yml
chunks/tool-bun/.bunfig.toml
chunks/tool-bun/Dockerfile
dazzle.yaml
tests/lang-python.yaml
tests/tool-bun.yaml

[Bun](https://bun.sh/) serves as a drop-in replacement for Node, and its binary (bun) is quite lightweight. Recently, some community members have asked if we could include it in our default image. And recently, bun hit the `v1.0` milestone, so it's probably the best time to add it, vercel also added it: https://vercel.com/changelog/bun-install-is-now-supported-with-zero-configuration
Fixes #
I built the full combo and pushed to my personal dockerhub: `axonasif/workspace-full-bun`
Try here: https://gitpod.io/#https://github.com/axonasif/test/tree/bun
/hold

Create workspace image for tool-bun chunk

---

CHANGELOG.md
chunks/lang-node/chunk.yaml
dazzle.yaml
tests/lang-node.yaml

Node 19 has reached End Of Life, so we're replacing it with the soon-to-be LTS, Node 20.
- https://nodejs.dev/en/about/releases/

Node 19 -> Node 20

---

chunks/tool-bun/chunk.yaml

Skips bun ahead to v1.0.6. 
https://github.com/oven-sh/bun/releases/tag/bun-v1.0.6

bun: `v1.0.6`

---

.autofix/fixers/update-lang-python.js

This changes the behavior to use https://github.com/endoflife-date/release-data/ as the source of truth for Python versions, hence removing `pyenv` as a dependency.

Python autofix update

---

.github/workflows/autofix.yml

This PR runs Autofix inside a GitHub Action, which results in us having more control over how it runs. Specifically, the Pull Requests raised will actually result from branches inside the repository, meaning that CI will be happy and automated tests will run correctly.
Fixes EXP-486

Autofix GitHub Action

---

chunks/tool-bun/chunk.yaml

Bumps Bun to https://github.com/oven-sh/bun/releases/tag/bun-v1.0.21

bun: v1.0.21

---

.github/promote-images.yml
.github/sync-containers.yml
CHANGELOG.md
README.md
chunks/lang-ruby/chunk.yaml
dazzle.yaml

Ruby 3.3.0 has been releases, and we are introducing a new image flavor along with it. We're also bumping Ruby 3 to use 3.3 by default.
https://github.com/ruby/ruby/releases/tag/v3_3_0

ruby: v3.3.0

---

.autofix/fixers/update-lang-python.js
.autofix/fixers/update-lang-ruby.js

Since the end of life version data format changed (see https://github.com/endoflife-date/release-data/issues/51), we need to adapt for our autofix to keep working.

Fix autofixes for python and ruby

---

CHANGELOG.md
chunks/lang-rust/chunk.yaml

This PR bumps rust to 1.77.0, the latest stable release of Rust.
As the previous Rust version contains an ICE, this is fairly important.
N/A
Run `rustc -V` in the gitpod terminal.
This does require https://www.gitpod.io/docs/introduction/languages/rust to be updated
```diff
Gitpod always comes with the latest available Rust toolchain pre-installed using [rustup](https://rustup.rs/). (As of this writing, the Rust version is
- 1.68.1.
+ 1.77.0.
```
However, either the repo has moved or I don't have access, so unfortunately I cannot create a new docs issue.
/hold

Bump Rust to 1.77.0

---

CHANGELOG.md
chunks/tool-docker/Dockerfile
tests/lang-java.yaml

Refer to https://github.com/gitpod-io/gitpod/issues/19662 for background, this is a temporary fix.
Related to #19662 
From a Gitpod workspace in this repo, test with:
```bash
./build-combo.sh base
```
/hold

[docker] pin to v26.0.1

---

.github/promote-images.yml
.github/sync-containers.yml
CHANGELOG.md
README.md
chunks/lang-java/chunk.yaml
dazzle.yaml
tests/lang-java.yaml

Adds Java 21 to keep up with the Zulu JDK LTS releases.
Adds the `lang-java:21` chunk as well as the `workspace-java-21` standalone image.
Fixes #1342

Introduce Java 21 LTS

---

chunks/lang-rust/chunk.yaml

Bump the image to https://github.com/rust-lang/rust/releases/tag/1.80.0

Bump Rust to 1.80

---

.github/promote-images.yml
.github/sync-containers.yml
CHANGELOG.md
README.md
chunks/lang-node/chunk.yaml
dazzle.yaml
tests/lang-node.yaml

Introduces images for Node 20 and 22 as well as removes Node 21 which has reached end of life in June.

Add Node 22 and remove Node 21

---

base/Dockerfile

For some reason, `rlwrap` is not being properly being set up and breaking `apt upgrade`. We include it now in the base image to hotfix the issue. This is more of a band-aid fix, and we should look into figuring it out properly.
Fixes ENT-751
1. Create a workspace (either a full new one or a `gp validate` "debug" one) based off of `filiptronicek/workspace-full:rlwrap`
2. Make sure you can execute `sudo apt update && sudo apt upgrade` in the newly-created workspace
Beware, this **will** take a while
1. Open this repo in a workspace
1. `./build-combo.sh full`
3. `docker pull localhost:5000/dazzle:full`
4. Create a `.gitpod.yml` file in an `example` folder in the repo root
5. `gp validate --workspace-folder="/workspace/workspace-images/example"`
6. Make sure you can execute `sudo apt update …

Include `rlwrap` in the base image

---

.github/workflows/push-main.yml

Adds retries to potentially fix 502s we've [been seeing](https://linear.app/gitpod/issue/ENT-749/502-error-when-pushing-images-to-docker-hub-for-main-build-of).

Retry syncing date-tagged images 2 times

---

.github/promote-images.yml
.github/sync-containers.yml
CHANGELOG.md
chunks/tool-dotnet/chunk.yaml
dazzle.yaml
tests/tool-dotnet.yaml

Remote dotnet 7, it is no longer in support, users should use dotnet 6 or 8, which are LTS and still in support.
This will help reduce the # of chunks and combinations we build, as well as the # of images we push to GAR and sync to Docker Hub.
Related:
* I checked, and could not find other images we can remove, such as old versions of Python, Ruby, Node, and Java.
Related to ENT-749
/hold

Remove dotnet 7

---

.github/workflows/push-main.yml

This will help keep synced images up-to-date on Docker Hub, so we don't accrue a backlog of unsynced content
> --keep-going If any errors occur during copying of images, those errors are logged and the process continues syncing rest of the images and finally fails at the end.
Ref: https://github.com/containers/skopeo/blob/main/docs/skopeo-sync.1.md
Related to ENT-749
/hold

Keep syncing, even if errors are encountered

---

.github/promote-images.yml
.github/sync-containers.yml
CHANGELOG.md
README.md
chunks/lang-node/chunk.yaml
dazzle.yaml
tests/lang-node.yaml

Last week, Node 22 became the active LTS release and Node 23 was introduced. Hence, this PR:
- introduces the `workspace-node-23`
- bumps `workspace-node` to node 23
- bumps `workspace-node-lts` to node 22

Node: bump LTS and introduce Node 23

---

.github/promote-images.yml
.github/sync-containers.yml
CHANGELOG.md
README.md
chunks/lang-java/chunk.yaml
dazzle.yaml
tests/lang-java.yaml

I propose this PR to add Java 23 chunk.
Fixes no issue created for this PR 
* No

✨ Add Java 23

---

CHANGELOG.md
chunks/tool-docker/Dockerfile

After a lot of awesome work from the team, we can finally ship the latest Docker into all workspaces. 
Fixes CLC-906

Upgrade Docker to v27

---

.github/workflows/dockerhub-release.yml

For a while now, we've only run the workflow manually (see [related internal Slack thread](https://gitpod.slack.com/archives/C01RC164G48/p1715011780302849?thread_ts=1714874731.424599&cid=C01RC164G48)). This makes the change more permanent to not force us to disable the workflow whenever we don't use it.

Do no promote latest Dockerhub images every Monday

---

base/Dockerfile

This should fix:
```
│    Library     │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version  │                            Title                             │
├────────────────┼────────────────┼──────────┼────────┼───────────────────┼────────────────┼──────────────────────────────────────────────────────────────┤
│ linux-libc-dev │ CVE-2024-26800 │ HIGH     │ fixed  │ 5.15.0-124.134    │ 5.15.0-125.135 │ kernel: tls: fix use-after-free on failed backlog decryption │
│                │                │          │        │                   │                │ https://avd.aquasec.com/nvd/cve-2024-26800                   │
│                ├────────────────┤          │        │                   │                ├──────────────────────────────────────────────────────────────┤ …
```

Bump base image

---

.autofix/fixers/update-lang-ruby.js
.autofix/fixers/update-tool-brew.js
chunks/tool-brew/Dockerfile

A hacky way to rebuild Homebrew when a new one comes out.

Homebrew autofix

---

chunks/lang-rust/Dockerfile

The `rust-analysis` and `rls` components are no longer installable. I've replaced them with `rust-analyzer` as the new LSP
See https://rust-lang.github.io/rustup/concepts/components.html#previous-components
The build shall pass

[lang-rust] don't install deprecated components

---

.github/CODEOWNERS

Remove @gitpod-io/team-engine from CODEOWNERS
