- full/Dockerfile
A collection of what Symfony, Drupal, Wordpress and Laravel use.
> Add more php extensions

- full/Dockerfile
Fixes gitpod-io/workspace-images#3
> [workspace-full] add maven

- full/Dockerfile
Fixes gitpod-io/workspace-images#6
> [npm] update to latest version

- full/Dockerfile
Fixes gitpod-io/workspace-images#14
> Update Maven to 3.5.4

- full/Dockerfile
Signed-off-by: Alex Tugarev <alex.tugarev@typefox.io>
> [python/pyls] use working version of pyls

- full/Dockerfile
fixing https://github.com/gitpod-io/gitpod/issues/107
> Bumped Go to 1.11.2

- full/Dockerfile
A minor quality of life improvement. Untested, but stolen from:
https://github.com/JanitorTechnology/dockerfiles/blob/9720db015514bd72b94cbd6d524e0ed3d9925a3c/ubuntu-dev/ubuntu-dev.dockerfile#L181
> Install bash completions for rustup

- full/Dockerfile
> Bump to latest stable Ruby: 2.6.0

- dotnet-vnc/Dockerfile
- dotnet/Dockerfile
This adds the .NET Core SDK images based from the VNC and the Full image respectively - as requested by @svenefftinge.
> .NET Core images

- full/Dockerfile
fixes https://github.com/gitpod-io/gitpod/issues/232
> Store local maven repo in /workspace/m2-repository

- full/Dockerfile
https://github.com/gitpod-io/gitpod/issues/337
> Store Gradle Build/Dependency Cache in /workspace

- .circleci/build_image.sh
> [circleci] Add specific version tags to pushed Docker images

- full/Dockerfile
Node.js `10.15.3` is the [current LTS](https://nodejs.org), so we should upgrade to it.
⚠️ However, this might break Theia.
> Upgrade to node 10.15.3 and yarn 1.13.0

- full-vnc/Dockerfile
- full-vnc/start-vnc-session.sh
fixes https://github.com/gitpod-io/workspace-images/issues/56
> Add Openbox window manager and add JavaFX compatibility libs

- full/Dockerfile
- full/apache2/apache2.conf
- full/apache2/envvars
- full/nginx/nginx.conf
Apache was installed already and Nginx is fairly lightweight. 
I think we can provide a lot of value by having both pre-configured for Gitpod.
TODO:
> Configure Apache and Nginx in workspace-full

- full/Dockerfile
breaks the build at the moment
> Don't install Java 12.0.1

- full/Dockerfile
- mysql/Dockerfile
- mysql/mysql-bashrc-launch.sh
[Apache] enable module "rewrite"
[MySQL] introduce lock to prevent conflicting launches
> improvements to MySQL and Apache

- .circleci/config.yml
- full/Dockerfile
- postgres/Dockerfile
- rethinkdb/Dockerfile
Fixes gitpod-io/workspace-images#93
> Upgrade to Ubuntu Disco Dingo

- .circleci/config.yml
- firefox/Dockerfile
Would be useful for Firefox and Thunderbird projects.
Also, I think this currently times out when run by Gitpod's image builder, hence the dedicated workspace image.
> [firefox] add a pre-configured build environment

- full/Dockerfile
- full/nvm-lazy.sh
Part of https://github.com/gitpod-io/gitpod/issues/697
> [full] Lazy-load NVM to speed up .bashrc execution

- full/Dockerfile
fixes https://github.com/gitpod-io/workspace-images/issues/103
> Add init sdkman and nvm init to .profile

- full/Dockerfile
To support `interactive view` of python extension.
> [python] Install notebook

- full/Dockerfile
- rethinkdb/Dockerfile
This should work around or fix #109.
> Upgrade all images to Clang 10

- .circleci/config.yml
- .circleci/dazzle_build_image.sh
- full/Dockerfile
- full/tests/lang-c.yaml
- full/tests/lang-go.yaml
- full/tests/lang-java.yaml
- full/tests/lang-node.yaml
- full/tests/lang-php.yaml
- full/tests/lang-python.yaml
- full/tests/lang-ruby.yaml
- full/tests/lang-rust.yaml
- full/tests/prologue.yaml
- full/tests/tool-brew.yaml
- full/tests/tool-nginx.yaml
`workspace-full` is a big image (> 8GiB) but with largely independent layers. Changing one layer (e.g. #117) needlessly invalidates others. 
[Dazzle](https://github.com/32leaves/dazzle) is an experimental Docker image builder that can build independent layers/"chunks". To ensure that those layers do not interfere with each other and the their merging has no adverse effects, dazzle supports testing the image.
This PR builds `workspace-full` using dazzle which should reduce workspace startup time variance considerably as the chances of a cache-miss are reduced. The image built using dazzle passes the same tests as the original image does (tests are part of this PR).
> Build and test workspace-full using dazzle

- full/Dockerfile
- full/tests/lang-java.yaml
- full/tests/lang-ruby.yaml
- full/tests/lang-rust.yaml
- full/tests/prologue.yaml
fixes Java, Ruby and Rust in non-login shells (like the ones opened in GItpod).
Try here: https://gitpod.io/#https://github.com/32leaves/test-repo/tree/test-wsfull-sdkfix
> Place stuff in .bashrc, not .bash_profile

- full/Dockerfile
- full/tests/lang-php.yaml
- full/tests/tool-nginx.yaml
Test this change via 
https://gitpod.io/#https://github.com/meysholdt/test
> Fix #128 by merging php and apache layers

- full/Dockerfile
- full/tests/lang-python.yaml
> Python: maintenance version upgrades

- full/Dockerfile
Bug fix release, no functional changes
> Bump python to 3.7.6

- gecko/Dockerfile
rr 5.3.0 is out: https://rr-project.org/
Also, we're pretty close to getting it to actually work on Gitpod!
> [gecko] Upgrade to rr 5.3.0

- full/Dockerfile
Fixes this build error:
```
package golang.org/x/tools/cmd/gopls: cannot find package "golang.org/x/tools/cmd/gopls" in any of:
/home/gitpod/go/src/golang.org/x/tools/cmd/gopls (from $GOROOT)
/home/gitpod/go-packages/src/golang.org/x/tools/cmd/gopls (from $GOPATH)
```
> [full] Fix gopls install

- full-vnc/novnc-index.html
Fixes https://github.com/gitpod-io/gitpod/issues/1239
> [VNC] Scaling

- .circleci/dazzle_build_image.sh
- full/Dockerfile
- full/tests/lang-rust.yaml
> Update Rust from 1.41.0 to 1.41.1

- .circleci/config.yml
Should fix workspace-dotnet build
> Increase no_output timeout

- full/Dockerfile
> Bump python to 3.7.7

- CHANGELOG.md
- dotnet-vnc/Dockerfile
- dotnet/Dockerfile
- full/Dockerfile
Fixes https://github.com/gitpod-io/workspace-images/issues/196
> [full] Upgrade from Ubuntu 19.04 → Ubuntu 20.04 LTS

- mysql/mysql.cnf
Fixes https://github.com/gitpod-io/gitpod/issues/1399
> [mysql] Fix MySQL image by updating mysql.cnf for MySQL 8

- .circleci/config.yml
- wasm/Dockerfile
This will be useful for the Web assembly guide later. The image is equipped with pretty much everything one would need for both Rust and C++ based WebAssembly development, more languages can be added later.
> [image] Add a workspace for Webassembly development.

- full/Dockerfile
bumps Go to the newly released 1.15
> [go] Bump to 1.15

- README.md
repair ❤️’s appearance on https://hub.docker.com/r/gitpod/workspace-full
> replace `:​heart:` with `❤️` for Docker

- gecko/Dockerfile
cc @sylvestre 
After this:
Before:
> Do shallow clone of gecko to clone quickly

- mongodb/Dockerfile
Attempt to fix https://github.com/gitpod-io/workspace-images/issues/308
> [mongodb] Upgrade to mongodb-org/4.4

- flutter/Dockerfile
- full-vnc/Dockerfile
- gecko/Dockerfile
- wasm/Dockerfile
optimize the git clone using --depth flag in term of size of clone
and also in term's of time taken to fetch the files and commit history
of whole repository .
More detail can be found at blog
https://www.atlassian.com/git/tutorials/big-repositories
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>
> optimization in git clone using --depth

- full/Dockerfile
Permission issues.
They are not maintained anymore, and won't build in go16
@jankeromnes
> [Full] fix golang build

- full/Dockerfile
Fix https://github.com/gitpod-io/workspace-images/issues/357
> [full]: add ninja-build

- base/Dockerfile
Fix https://github.com/gitpod-io/workspace-images/issues/239
> [base] add basic shell

- wasm/Dockerfile
https://github.com/WebAssembly/wabt
WABT: The WebAssembly Binary Toolkit
This is frequently used and quite useful for WebAssembly development, so really good to have it.
> [wasm]: add wabt

- full/Dockerfile
Fixes https://github.com/gitpod-io/gitpod/issues/4508
> [PATH] Add /usr/games

- full-vnc/start-vnc-session.sh
Credit to @ghuntley for identifying the root cause: https://github.com/gitpod-io/workspace-images/issues/441#issuecomment-875249357
Fixes https://github.com/gitpod-io/workspace-images/issues/441
Fixes https://github.com/gitpod-io/gitpod/issues/4770
> [full-vnc] Fix Virtual Desktop (rename noVNC/utils/launch.sh → noVNC/utils/novnc_proxy)

- full/Dockerfile
Only update go to 1.16.6 in full image
> Update go to 1.16.6

- full/Dockerfile
A basic util to support cargo workspaces, super useful.
> [full]: add cargo-workspaces to cargo utils

- full/Dockerfile
- Upgrade golang to latest version (1.17.1)
> full: upgrade go to 1.17.1

- base/Dockerfile
> fix: check if .bashrc.d is empty on base image

- full/Dockerfile
Enable the upgrade to the latest docker version
```release-note
Upgrade to the latest docker stable version
```
> Upgrade to docker 20

- full/Dockerfile
fix https://github.com/gitpod-io/workspace-images/issues/472
> [full]: share env path better between users

- full/Dockerfile
- full/tests/lang-php.yaml
Fixes https://github.com/gitpod-io/workspace-images/issues/545
Tested via included dazzel tests. 
```release-note
- !Upgrade to PHP8 in workspace-full from 7.4.3
```
> feat(workspace-full): upgrade to php8 from php7

- full/Dockerfile
Fixes #
```release-note
feat(workspace-full): bump go to 1.17.3
```
> feat(workspace-full): bump go to 1.17.3

- full/Dockerfile
- full/tests/tool-clojure.yml
add Clojure installation to 'full' image
Fixes #559 
1. build images
2. run "clj", should start clojure repl
Adding Clojure to base image
* Yes : https://github.com/gitpod-io/website/issues/1288
> feat(workspace-full): add clojure

- .github/workflows/push-main.yml
Use the correct host to log into GAR
[Fixes this build error](https://github.com/gitpod-io/workspace-images/actions/runs/1763358311) 
This will run once merged
```release-note
NONE
```
> Use correct env var to log into GAR

- .github/workflows/push-main.yml
Depends on https://github.com/gitpod-io/workspace-images/pull/645/commits
> Add update of latest tag for workspace-full

- CONTRIBUTING.md
- README.md
Update contribution guide and readme.
Fixes https://github.com/gitpod-io/workspace-images/issues/572
You can navigate to the branch and open the README.md and the CONTRIBUTING.md file to check if the text renders correctly.
```release-note
Update contribution guide
```
> docs: Update Contribution guide

- chunks/tool-nginx/Dockerfile
- tests/tool-nginx.yaml
> Update composer and add tests

- .github/promote-images.yml
- .github/workflows/push-main.yml
Updated GAR -> Dockerhub using a dedicated step
Added all available images to the list of images that need to be synced.
> Sync all images from GAR to dockerhub

- .github/workflows/push-main.yml
Tag all the images to latest that are supposed to be pushed to dockerhub
Fixes #
```release-note
```
> Add missing latest tagging

- chunks/lang-node/Dockerfile
- tests/lang-node.yaml
Fixes #665
```release-note
```
> feat: add pnpm for Node.js

- chunks/lang-rust/Dockerfile
- tests/lang-rust.yaml
- About #464
> I came across three solutions
> 1. Wrapping `rustup` with a bash script to unset `CARGO_HOME` variable to make it use the original `$HOME/.cargo` dir. Might not be future proof. (Current proposed workaround)
> 2. Greedily symlinking everything from `$HOME/.cargo/bin` to `/workspace/.cargo/bin`(Custom `CARGO_HOME`). Might cause unexpected issues.
> 3. Using shell specific aliases to wrap `rustup` in a quite neat way, ~~what I ended up with.~~
- About #506 
> Previously this:
> https://github.com/gitpod-io/workspace-images/blob/7d640a13abc662a459f885f7a432e8d9337d9a4e/chunks/lang-rust/Dockerfile#L27
> was being run with having custom `CARGO_HOME`(**/workspace/.cargo**). But `/workspace` is non-existent in the actual container image since `/workspace` is basically mounted when …
> refactor(lang-rust): Setting up Rust environment properly

- .github/workflows/triage.yml
Edit error of missing usage of `slug` variable.
Fixes # NA
This PR's triage action should succceed.
```release-note
NA
```
> Fix error of missing usage of var in actions

- .github/workflows/pull-request.yml
- .github/workflows/push-main.yml
- .gitpod.yml
Bump dazzle from v0.1.6 to v0.1.7
https://github.com/gitpod-io/dazzle/releases/tag/v0.1.7
Fixes #721 
Make sure that pyenv is taken precedence better than the system python.
```console
$ curl -sSL https://github.com/gitpod-io/dazzle/releases/download/v0.1.7/dazzle_0.1.7_Linux_x86_64.tar.gz | sudo tar -xvz -C /usr/local/bin
$  ./dazzle-up.sh 
$ docker run --rm localhost:5000/dazzle:python env | grep ^PATH
PATH=/workspace/.pip-modules/bin:/home/gitpod/.pyenv/bin:/home/gitpod/.pyenv/shims:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
$ docker run --rm localhost:5000/dazzle:python which python3
/home/gitpod/.pyenv/shims/python3
$ docker run --rm localhost:5000/dazzle:python which python
/home/gitpod/.pyenv/shims/python
$ docker run --rm localhost:5000/dazzle:full env | grep …
```
> Bump dazzle from v0.1.6 to v0.1.7

- CONTRIBUTING.md
Update contributing guide with about changes in release workflow [[1](https://github.com/gitpod-io/workspace-images/pull/753)], [[2](https://github.com/gitpod-io/workspace-images/commit/0691a50f42b5b74225eb13da65a50ec65ca80873)]
Fixes NA
```release-note
None
```
> Update readme with recent wflow changes

- chunks/lang-go/chunk.yaml
- chunks/lang-node/chunk.yaml
- chunks/lang-ruby/chunk.yaml
- chunks/tool-nix/chunk.yaml
- tests/lang-go.yaml
- tests/lang-node.yaml
- tests/lang-ruby.yaml
- tests/tool-nix.yaml
Remove variants that are not being published.
Fixes https://github.com/gitpod-io/workspace-images/issues/669
NA
```release-note
Remove chunk variants which are not being used or not being published to Dockerhub
```
> Remove variants that are not being published

- chunks/tool-chrome/Dockerfile
- dazzle.yaml
- tests/tool-chrome.yaml
close https://github.com/gitpod-io/workspace-images/issues/457 
close #254
close #515
> feat: add chrome and electron support

- chunks/lang-go/Dockerfile
- chunks/lang-go/chunk.yaml
- dazzle.yaml
- tests/lang-go.yaml
> Bump Go to 1.18

- README.md
Link to documentation for usage examples
Fixes #510
n.a.
```release-note
None
```
> Link to documentation for usage examples

- .autofix/fixers/update-lang-python.js
- chunks/lang-python/chunk.yaml
- chunks/lang-rust/Dockerfile
- tests/lang-rust.yaml
Implements a local Autofix fixer for Python variants, based on https://github.com/autofix-dev/autofix/blob/master/fixers/upgrade-pyenv-tools.js
Fixes #
```release-note
NONE
```
> Autofix Python variants 

- chunks/lang-go/Dockerfile
Please check #765 for the reason of this change 🙏 
```release-note
```
Related: https://github.com/gitpod-io/website/pull/1947
> fix(chunks/lang-go): Be context aware of /workspace

- chunks/lang-go/chunk.yaml
- dazzle.yaml
Upgraded go from 1.18.2 to 1.18.3
> Upgraded go to 1.18.3

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
Updates the past announcements published on 2022-01 via #593.
Fixes #861
See README.md on GitHub.
n/a
* No
> Update announcements published on 2022-01

- chunks/lang-go/chunk.yaml
- dazzle.yaml
https://groups.google.com/g/golang-announce/c/nqrv9fbR0zE
```release-note
Update go to v1.18.4
```
> Update go to v1.18.4

- .github/workflows/push-main.yml
Ref: https://github.com/gitpod-io/workspace-images/actions/runs/2672709701
> Mitigate timeouts with Google

- .github/workflows/dockerhub-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/push-main.yml
- .gitpod.Dockerfile
- base/Dockerfile
- base/default.gitconfig
Force build of base image to update git to latest version
> Install latest git version

- base/Dockerfile
> Simplify git configuration

- .github/promote-images.yml
- .github/sync-containers.yml
- chunks/tool-yugabytedb/Dockerfile
- chunks/tool-yugabytedb/chunk.yaml
- dazzle.yaml
- tests/tool-yugabytedb.yaml
YugabyteDB maintains two release channels [stable](https://docs.yugabyte.com/stable/releases/versioning/#stable-releases) and [preview](https://docs.yugabyte.com/preview/releases/versioning/#preview-releases). The stable channel is the production version, and the preview channel will have the latest (beta) features ahead of the stable releases. Both are open source, and the community uses releases from both channels.
This PR is to support the versions released through both channels.
> [YugabyteDB] Add chunk.yaml to support stable and preview release versions of YugabyteDB

- chunks/lang-elixir/Dockerfile
- tests/lang-elixir.yaml
Fixes failing builds of #888 #891
```release-note
```
> fix(lang-elixir): Tests failing because of version mismatch

- base/Dockerfile
- chunks/lang-python/Dockerfile
- chunks/lang-python/pyenv.d/exec/gitpod.bash
- chunks/lang-python/python_bash_hook
Fixes:
- [#poetry and virtualenv errors with PIP_USER](https://discord.com/channels/816244985187008514/999898090926510140) (on discord)
- #870
```release-note
```
> fix(lang-python): Only alter PIP variables for pip commands and add poetry support

- chunks/lang-python/python_hook.bash
Fixes:
- https://github.com/gitpod-io/workspace-images/issues/909
- https://discord.com/channels/816244985187008514/1013766836044709890
```release-note
fix: pyenv integration with vscode and prebuilds
```
> fix: pyenv integration with vscode and prebuilds

- base/Dockerfile
Install `ping` utility
Fixes #
1. In a built dev image, run `ping`
```release-note
NONE
```
> [base] Install ping utility

- chunks/lang-python/python_hook.bash
- tests/lang-python.yaml
> fix: python extension settings write

- chunks/lang-go/chunk.yaml
Make latest releases (as per <https://go.dev/dl/>) available.
Fixes #
```release-note
```
> update to Go 1.19.1

- chunks/lang-go/chunk.yaml
- dazzle.yaml
> bump go version to 1.19.2 and 1.18.7

- chunks/lang-rust/Dockerfile
fix https://github.com/gitpod-io/workspace-images/issues/930
> feat: bump rust to 1.64

- chunks/lang-node/Dockerfile
- tests/lang-node.yaml
Fixes https://github.com/gitpod-io/workspace-images/issues/639
Fixes https://github.com/gitpod-io/workspace-images/issues/913
Also fix pnpm setup issue.
build and test works.
```
docker build -t test --build-arg base=gitpod/workspace-base --build-arg NODE_VERSION=18.7.0 
```
I also add test cases in yml too.
```release-note
```
> fix: package manager bugs for Node.js

- .markdownlint.yaml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- README.md
This PR will fix CI. e.g. https://github.com/gitpod-io/workspace-images/actions/runs/3308212305/jobs/5472037207
NONE
```release-note
NONE
```
> Adjust the config of markdownlint to reality

- chunks/tool-nginx/Dockerfile
- tests/tool-nginx.yaml
- Simplified install of composer by just copying it from the official docker image
- Added PHP-FPM to speed up [Symfony-CLI](https://symfony.com/doc/current/setup/symfony_server.html)
> feat: update composer to 2.4.4

- chunks/lang-go/chunk.yaml
- dazzle.yaml
> update Go to 1.19.3 and 1.18.8

- chunks/lang-go/chunk.yaml
- dazzle.yaml
> update Go to 1.19.4 and 1.18.9

- chunks/lang-rust/Dockerfile
Rust 1.66.0 introduces some features I'd like to use.
> feat: bump rust to 1.66

- .gitpod.Dockerfile
Use Jammy image in the Gitpod Workspace.
> Update Gitpod Workspace image to Jammy

- .github/workflows/triage.yml
This should make it, so that we can continue to leverage the zapier automation which notifies teams.
> Add team: ide label for new issues

- CONTRIBUTING.md
Adds a section to the CONTRIBUTING.md file that instructs how to perform an end-to-end test, testing in a proper Debug (`gp validate`) Workspace.
> Add manual testing steps

- .github/workflows/dockerhub-release.yml
Use a container instead of an Ubuntu package, removing the external Suse repository.
> Improve skopeo execution

- .github/workflows/push-main.yml
A couple [steps](https://github.com/gitpod-io/workspace-images/actions/runs/5542559100/jobs/10117389052) are failing due to syntax errors.
I did some clean-up and defensive changes to help.
> [.github] fixup the push-main.yaml

- chunks/lang-rust/Dockerfile
Related https://github.com/gitpod-io/website/pull/3627
> feat: Bump Rust to `1.70.0`

- chunks/tool-yugabytedb/chunk.yaml
- dazzle.yaml
- tests/tool-yugabytedb.yaml
Updating YBDB to the latest stable and preview versions
> [YBDB] Image - version upgrade

- .github/workflows/push-main.yml
- .github/workflows/push-main/upload_image.sh
> [.github] simplify parallelism

- .github/workflows/push-main.yml
This works fine in a Gitpod workspace. Let's try working around the error.
🤞
> [.github] push-main.yml has a syntax error at runtime only

- .github/workflows/pull-request.yml
- .github/workflows/push-main.yml
- .github/workflows/triage.yml
Building on top of ENG-489, this PR utilizes our own runners on GCP.
Fixes EXP-48
> Run workflows on our runners

- chunks/lang-node/chunk.yaml
> Bump Node 18

- .github/workflows/dockerhub-release.yml
Fix a linting issue preventing the job from running.
Fixes n/a
Merge to main, run the job.
/hold
> [.github] steps must have unique IDs

- chunks/lang-ruby/chunk.yaml
- tests/lang-ruby.yaml
Patch updates for Ruby
Fixes #
/hold
> Bump Ruby versions

- chunks/tool-bun/Dockerfile
- chunks/tool-bun/chunk.yaml
- dazzle.yaml
Updates to https://github.com/oven-sh/bun/releases/tag/bun-v1.0.3
> Chunkify and update Bun

- chunks/tool-bun/chunk.yaml
Bumps to https://github.com/oven-sh/bun/releases/tag/bun-v1.0.4
> Bun `1.0.4`

- .github/promote-images.yml
- .github/sync-containers.yml
- CHANGELOG.md
- README.md
- chunks/lang-python/Dockerfile
- chunks/lang-python/chunk.yaml
- chunks/lang-python/python_hook.bash
- dazzle.yaml
- tests/lang-python.yaml
Accommodates the latest Python release.
> Python `3.12`

- chunks/lang-go/chunk.yaml
As the title indicates, this updates the thing to the version.
> Update Go to `1.21.2`

- .autofix/fixers/update-lang-ruby.js
- tests/lang-ruby.yaml
Adds a script which updates Ruby versions automatically
> Introduce autofix for ruby

- chunks/lang-rust/Dockerfile
> lang-rust: use default profile

- chunks/tool-bun/chunk.yaml
Updates bun to https://github.com/oven-sh/bun/releases/tag/bun-v1.0.8
> bun: 1.0.8

- chunks/lang-go/chunk.yaml
> Autofix: update-lang-go

- .autofix/fixers/update-tool-bun.js
- chunks/lang-go/chunk.yaml
They update a lot, so it's worth giving autofixing a shot.
> Autofix `tool-bun`

- CHANGELOG.md
- chunks/lang-rust/chunk.yaml
> feat: bump rust to 1.74.1

- chunks/tool-bun/chunk.yaml
Update bun to https://github.com/oven-sh/bun/releases/tag/bun-v1.0.20
> bun: v1.0.19

- chunks/tool-brew/Dockerfile
> feat: upgrade homebrew to 4.2

- CHANGELOG.md
- README.md
- chunks/tool-nix/chunk.yaml
- dazzle.yaml
- tests/tool-nix.yaml
Bumps nix, which has not seen an update in quite a while.
Also adds it along with yugabyte to the readme.
> Update nix and readme

- chunks/lang-python/Dockerfile
- chunks/tool-docker/Dockerfile
- tests/tool-docker.yaml
See https://gitpod.slack.com/archives/C01RC164G48/p1705660282591359
Fixes #
/hold
> Rebuild Python images and update `docker-compose`

- chunks/tool-yugabytedb/chunk.yaml
- tests/tool-yugabytedb.yaml
Update v20 to fix build errors
> Fix yugabyte-db build

- chunks/lang-python/Dockerfile
To avoid CVE-2022-40897
Fixes ENG-1705
```
docker run --rm -it gitpod/workspace-python-3.8:2024-01-24-09-19-42
gitpod ~ $ source /home/gitpod/.local/share/pypoetry/venv/bin/activate
(venv) gitpod ~ $ pip install --upgrade setuptools
Requirement already satisfied: setuptools in ./.local/share/pypoetry/venv/lib/python3.8/site-packages (56.0.0)
Collecting setuptools
Downloading setuptools-69.0.3-py3-none-any.whl.metadata (6.3 kB)
Downloading setuptools-69.0.3-py3-none-any.whl (819 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 819.5/819.5 kB 5.8 MB/s eta 0:00:00
Installing collected packages: setuptools
Attempting uninstall: setuptools
Found existing installation: setuptools 56.0.0
Uninstalling setuptools-56.0.0:
Successfully uninstalled setuptools-56.0.0
Successfully installed …
```
> [python] update setuptools for poetry

- CHANGELOG.md
- chunks/lang-python/Dockerfile
- chunks/lang-python/chunk.yaml
- chunks/tool-bun/chunk.yaml
Bumps bun to its first minor release since v1 and patches Python.
If this is reviewed later tomorrow, I'll also push updates to Bun `v1.1.1`, it [should ship soon](https://twitter.com/jarredsumner/status/1775010398825288137).
> Bump Bun and Python

- .github/promote-images.yml
- .github/sync-containers.yml
- CHANGELOG.md
- README.md
- chunks/lang-ruby/chunk.yaml
- dazzle.yaml
As it reached EOL, we are no longer going to update these images.
> Deprecate Ruby 3.0

- chunks/lang-rust/chunk.yaml
> feat: upgrade rust to 1.77.2

- .github/workflows/dockerhub-release.yml
The action is intermittently failing: https://github.com/gitpod-io/workspace-images/actions/runs/8687217735
Fixes n/a
Merge to main, trigger the job manually.
/hold
> [.github] retry skopeo copy for sync latest

- .github/workflows/dockerhub-release.yml
Retrying twice helped, but, we're still seeing trouble.
Fixes n/a
Same as #1327 
/hold
> [.github] increase # of retries to sync latest

- .github/CODEOWNERS
Adjustment after recent team changes
Fixes #
/hold
> [dev] Make Team Enterprise co-own everything

- tests/lang-java.yaml
Fixes a failing test, which is a regression from #1384 (silly me)
> fix java test

- CHANGELOG.md
- chunks/lang-go/chunk.yaml
- dazzle.yaml
See https://go.dev/doc/go1.23 for more
> Bump Go to 1.23

- base/Dockerfile
- chunks/lang-ruby/Dockerfile
- chunks/lang-ruby/chunk.yaml
- chunks/lang-ruby/install.sh
- tests/lang-ruby.yaml
Fixes to unblock #1412 
Either trust me on this one (I tried these), or:
1. `./build-chunk ruby-3.3`
2. Make a `.gitpod.yml` with `image: localhost:5000/dazzle:ruby-3.3` inside `test`
3. `gp validate --workspace-folder /workspace/workspace-images/test`
> Fix Ruby build

- chunks/lang-python/Dockerfile
- chunks/tool-yugabytedb/Dockerfile
> Bump pyenv

- .github/workflows/dockerhub-release.yml
- .github/workflows/push-main.yml
After this version, we've experienced nothing but timeouts when syncing on push to main.
Ref: https://gitpod.slack.com/archives/C01RC164G48/p1726001852662349?thread_ts=1725887846.208599&cid=C01RC164G48
Fixes [ENT-749](https://linear.app/gitpod/issue/ENT-749)
Land on main, observe the action is successful in pushing to Docker Hub, and finishes w/o error (presently it times out).
/hold
> Pin skopeo to last version that worked well

- chunks/lang-rust/chunk.yaml
> feat: bump rust to 1.82

- .autofix/fixers/update-lang-rust.js
Fixes #
- Open workspace with current PR
- Exec `npx autofix` and see the latest commit
/hold
> Add autofix `lang-rust`

- CHANGELOG.md
Adds an entry for https://github.com/gitpod-io/workspace-images/pull/1440
> Update CHANGELOG.md with Rust release

- tests/lang-java.yaml
Makes builds pass on `main` again, hopefully.
> Fix java tests

- chunks/lang-rust/Dockerfile
TODO:
Fixes [#10974](https://app.usepylon.com/issues?conversationID=3d964a57-38d0-4cb3-9785-89cbdfb5e4e8)
- Create a workspace from here using RustRover IDE: https://github.com/gitpod-io/optimus/tree/test_workspace-rust
- Open `src/main.rs`. Click on the play button on top-right. You should see that it's not rebuilding the whole project from scratch.
/hold
> Fix Rust toolchain environment issue on RustRover

- CHANGELOG.md
- chunks/lang-go/chunk.yaml
- dazzle.yaml
> [lang-go] Bump to `1.24`

- chunks/lang-python/Dockerfile
`uv` is a faster alternative to poetry https://docs.astral.sh/uv/ 
Fixes #
/hold
> Update Dockerfile to support uv

- chunks/lang-python/Dockerfile
Python 3.13 chunk is [failing](https://github.com/gitpod-io/workspace-images/actions/runs/15687869645/job/44205686234) dazzle build
Fixes CLC-1437
Build passes in workspace: `./build-chunk.sh -c lang-python:3.13`:
```
> importing cache manifest from localhost:5000/dazzle:lang-python-3.13--e6fd1681e0201eee6b10c1da50b944be3011046b97660801f2a7b52b89612d59--full:
------
building chunked image                      chunk="lang-python:3.13" ref=localhost:5000/dazzle/lang-python:3.13 
INFO[0235] trying next host - response was http.StatusNotFound  host="localhost:5000"
step 00      pushing config                              dest="localhost:5000/dazzle/lang-python:3.13" 
step 01      pushing layers                              dest="localhost:5000/dazzle/lang-python:3.13" 
step 02      copying …
```
> [python] bump pyenv to fix build

- .github/CODEOWNERS
> Remove Team Experience from CODEOWNERS

- tests/lang-java.yaml
> fix java test expectations
